" Recursive search for files with :find
set path+=**

" Nice menu for find search
set wildmenu

" Tree view in file browser
"let g:netrw_liststyle=3

" Vundle
set nocompatible
filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" syntax auto-completion
Plugin 'Valloric/YouCompleteMe'
" GDB
"Plugin 'vim-scripts/Conque-GDB'
let g:ConqueTerm_Color = 2         " 1: strip color after 200 lines, 2: always with color
let g:ConqueTerm_CloseOnEnd = 1    " close conque when program ends running
let g:ConqueTerm_StartMessages = 0 " display warning messages if conqueTerm is configured incorrectly  

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on
set encoding=utf-8
" ~Vundle

execute pathogen#infect()

" Change swap files directory
set directory=~/.vim/swapfiles//

" cursor as | in insert mode
let &t_SI = "\<esc>[5 q"
let &t_SR = "\<esc>[3 q"
let &t_EI = "\<esc>[2 q"

" Switch buffers quickly
map <F9> :bprevious<CR>
imap <F9> <Esc>:bprevious<CR>
vmap <F9> <Esc>:bprevious<CR>
map <F10> :bnext<CR>
imap <F10> <Esc>:bnext<CR>
vmap <F10> <Esc>:bnext<CR>

" Control-t to save
"nmap <c-t> :w<CR> 
imap <c-t> <Esc>:w<CR>
vmap <c-t> <Esc>:w<CR>

" Expand current directory
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" Cursor can go past last char
set virtualedit=all

" Fixes some bad terminal
set background=dark

let mapleader = " "
syntax on

" Filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

set wildmode=list:longest

" Show cursor row and column position
set ruler

" Show always status bar
set laststatus=2

" Make backspace work normally in insert mode
set backspace=indent,eol,start

" Set files with extension .md to be recognized as markdown.
au BufNewFile,BufRead *.{md,mdown,mkd,mkdn,markdown,mdwn} set filetype=markdown

" Turn on line number
set number

" Force saving files that require root permission 
cnoremap w!! w !sudo tee > /dev/null %

" Use system clipboard to copy/paste. Needs vim-gtk
set clipboard=unnamedplus

" Automatically source .vimrc on write
autocmd bufwritepost .vimrc source $MYVIMRC | redraw

" Leader s: invoke search char plug in
map <Leader> <Plug>(easymotion-prefix)

" Programming bindings

autocmd filetype cpp nnoremap <F2> :YcmCompleter GoTo<CR>
autocmd filetype cpp nnoremap <F3> :YcmCompleter FixIt<CR>
" -D_GLIBCXX_USE_CXX11_ABI=0 because gdb otherwise can't print global variables
autocmd filetype cpp nnoremap <F4> :w <bar> exec '!g++ -DGIL -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 -g '.shellescape('%').' -o '.shellescape('%:r')<CR>
autocmd filetype cpp nnoremap <F5> :exec '!./'.shellescape('%:r')<CR>
autocmd filetype cpp nnoremap <F6> :exec '!gdb ./'.shellescape('%:r')<CR>

autocmd filetype python nnoremap <F5> :exec '!python '.shellescape('%')<CR>

" Set a default YCM config to avoid error on loading cpp files.
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
