execute pathogen#infect()

" cursor as | in insert mode
let &t_SI = "\<esc>[5 q"
let &t_SR = "\<esc>[3 q"
let &t_EI = "\<esc>[2 q"

" Use comma for leader
let mapleader = ","

" Control-t to save
nmap <c-t> :w<CR> 
imap <c-t> <Esc>:w<CR>
vmap <c-t> <Esc>:w<CR>

" Use single leader in easymotion
map <leader> <Plug>(easymotion-prefix)

" ,r to execute current line
nmap <leader>r :exec '!'.getline('.')<CR>
",c to copy to Mac clipboard
vmap <leader>c :w !pbcopy<CR>

" expand current directory
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" cursor can go past last char
set virtualedit=all

syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

set wildmode=list:longest


" show cursor row and column position
set ruler

" show always status bar
set laststatus=2

" no beeping
" set visualbell

" make backspace work normally in insert mode
set backspace=indent,eol,start


colorscheme sprinkles

" set files with extension .md to be recognized as markdown.
au BufNewFile,BufRead *.{md,mdown,mkd,mkdn,markdown,mdwn} set filetype=markdown

" turn on line number
set number

" Syntastic, syntax checker
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0
"

" Autoreload vimrc
"if has ('autocmd') " Remain compatible with earlier versions
" augroup vimrc     " Source vim configuration upon save
"    autocmd! BufWritePost $MYVIMRC source % | echom "Reloaded " . $MYVIMRC | redraw
"    autocmd! BufWritePost $MYGVIMRC if has('gui_running') | so % | echom "Reloaded " . $MYGVIMRC | endif | redraw
"  augroup END
"endif " has autocmd
